(()=>{
  const P=window.MDPack,Z=window.MDZip;
  const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
  let watchTimer=null,watchHandle=null,watchStamp='';
  let quarantine=new Set(JSON.parse(localStorage.getItem('mdQuarantine')||'[]'));
  let binary=JSON.parse(localStorage.getItem('mdBinaryState')||'null');
  const knowledge=[
    ['Mixin conflict','Mixins patch Minecraft or mod classes at runtime. Injection failures usually mean the target bytecode changed, another mod modified the same area, or the mixin was built for another version.','Compare recently changed mods, inspect mixin configs, then binary-search the smallest suspect group.'],
    ['Missing dependency','A mod declares another mod or library as mandatory but it is absent from the pack.','Install the required dependency in a compatible version for the same Minecraft version and loader.'],
    ['Duplicate mod ID','Two JARs declare the same mod ID. Loaders normally reject this before the game can finish starting.','Keep only one compatible copy. Check embedded JARs as well as the top-level mods folder.'],
    ['NoSuchMethodError','Compiled code is calling a method that does not exist in the loaded version of a dependency.','Match the versions of the calling mod and the library/API it was compiled against.'],
    ['NoClassDefFoundError','A class expected at runtime is missing or failed to initialize.','Check dependencies, wrong loader variants, removed APIs, and the earliest Caused by line.'],
    ['Java mismatch','Modern Minecraft generations require specific Java majors.','Use the Java major recommended by the Doctor for the detected Minecraft version; avoid mixing launcher-bundled and system Java accidentally.'],
    ['Out of memory','The JVM or native layer ran out of allocatable memory.','Check -Xmx, native allocation, huge resource packs, shaders, world generation, and memory leaks before simply assigning all system RAM.'],
    ['Native / GPU crash','The JVM exited in native code, often OpenGL, a driver DLL/SO, LWJGL, or a native mod library.','Update or roll back drivers, disable shaders/overlays, test without renderer mods, and inspect hs_err_pid logs.'],
    ['Registry / world problem','Saved worlds persist registry references. Removing content mods can leave missing blocks, entities, dimensions, or datapack registrations.','Back up the world, restore removed content mods, or test a fresh world to distinguish pack startup from world-state failure.'],
    ['Client/server side mismatch','A client-only mod is present on a dedicated server, or required gameplay content differs between client and server.','Use the Client vs Server Doctor and align common gameplay mods while keeping UI/render mods client-side.'],
    ['Access widener / transformer','These files alter class/member accessibility and are sensitive to mappings and Minecraft versions.','Inspect the mod that owns the widener/transformer and verify it targets the exact loader and Minecraft version.'],
    ['Datapack / resource error','JSON data, recipes, tags, loot tables, models, or pack metadata failed to parse.','Open the exact reported path, validate JSON, then check namespace and referenced resource paths.'],
    ['Performance / tick lag','Server tick time exceeded the 50 ms target or startup contains long stalls.','Use Startup Profiler and Performance Doctor; isolate worldgen, entity, script, and heavy content mods before changing JVM flags.']
  ];
  function core(){try{return typeof latestAnalysis!=='undefined'?latestAnalysis:null}catch{return null}}
  function h(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function fmt(n){return Number(n||0).toLocaleString()}
  function severityClass(s){return ['critical','high','medium','low'].includes(s)?s:'low'}
  function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
  async function copy(text,button){await navigator.clipboard.writeText(text);if(button){const old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,1200)}}
  function init(){
    const top=qs('.topbar');if(top&&!qs('#labToggle')){const b=document.createElement('button');b.id='labToggle';b.className='lab-toggle';b.textContent='🧪 Doctor Lab';top.appendChild(b)}
    const main=qs('main');const lab=document.createElement('section');lab.id='doctorLab';lab.className='doctor-lab panel hidden';lab.innerHTML=markup();main.appendChild(lab);bind();renderSnapshots();renderBinary();renderQuarantine();renderKnowledge('');consumeShare();
    ['#analyzeBtn','#loadSample'].forEach(sel=>qs(sel)?.addEventListener('click',()=>setTimeout(()=>{refreshRuntime();captureFingerprint(false);renderFixPlan();renderHealth()},20)));
  }
  function markup(){return `
    <div class="lab-head"><div><span class="eyebrow">ADVANCED WEB SUITE</span><h2>Doctor Lab</h2><p>Pack inventory, dependency checks, diffing, interactive isolation, runtime profiling, snapshots and sanitized sharing — all in-browser.</p></div><button class="ghost" id="closeLab">Close</button></div>
    <div class="lab-tabs">
      <button class="lab-tab active" data-lab="pack">📦 Pack Scanner</button><button class="lab-tab" data-lab="diff">↔ Diff & Rollback</button><button class="lab-tab" data-lab="debug">🧬 Debug Lab</button><button class="lab-tab" data-lab="health">📈 Health</button><button class="lab-tab" data-lab="tools">🛠 Share & Tools</button>
    </div>
    <div class="lab-pane" id="lab-pack">
      <div class="lab-grid two"><section class="lab-card"><h3>Mods / instance scanner</h3><p class="muted">Upload a ZIP, MRPACK, JAR, datapack/resource-pack ZIP, or select a full instance folder. JAR metadata is inspected locally.</p><div class="row"><select id="packRole"><option value="client">Client pack</option><option value="server">Dedicated server pack</option></select><button class="primary" id="pickPack">Choose archive/JAR</button><button class="secondary" id="pickFolder">Choose folder</button><button class="secondary" id="pickPrism">Open Prism instance</button></div><input type="file" id="packInput" hidden accept=".zip,.mrpack,.jar" multiple><input type="file" id="folderInput" hidden webkitdirectory multiple><div class="scan-status" id="packStatus">No pack scanned.</div></section><section class="lab-card"><h3>Pack health</h3><div id="packHealth" class="health-dashboard empty-mini">Scan a pack to calculate dependency, compatibility, config and integrity health.</div></section></div>
      <div id="packResults" class="lab-stack"></div>
    </div>
    <div class="lab-pane hidden" id="lab-diff">
      <div class="lab-grid two"><section class="lab-card"><h3>Working pack</h3><div class="row"><select id="workingRole"><option value="client">Client</option><option value="server">Server</option></select><button class="primary" id="pickWorking">Choose working ZIP/MRPACK</button></div><input id="workingInput" type="file" hidden accept=".zip,.mrpack,.jar"><div id="workingStatus" class="scan-status">Not loaded.</div></section><section class="lab-card"><h3>Broken / current pack</h3><div class="row"><select id="brokenRole"><option value="client">Client</option><option value="server">Server</option></select><button class="primary" id="pickBroken">Choose broken ZIP/MRPACK</button></div><input id="brokenInput" type="file" hidden accept=".zip,.mrpack,.jar"><div id="brokenStatus" class="scan-status">Not loaded.</div></section></div>
      <div class="row diff-actions"><button class="primary" id="runDiff">Compare packs</button><button class="secondary" id="clientServer">Client vs Server Doctor</button><button class="secondary" id="saveSnapshot">Save current snapshot</button></div><div id="diffResults" class="lab-stack"></div><section class="lab-card"><div class="section-head"><h3>Snapshots & change timeline</h3><button class="ghost" id="refreshSnapshots">Refresh</button></div><div id="snapshotList"></div></section>
    </div>
    <div class="lab-pane hidden" id="lab-debug">
      <div class="lab-grid three"><section class="lab-card"><h3>Crash fingerprint</h3><p id="fingerprintBox" class="muted">Analyze a log first.</p><button class="secondary" id="saveFingerprint">Save / compare fingerprint</button></section><section class="lab-card"><h3>Folder Watch</h3><p class="muted">Chrome/Edge: grant access to a Minecraft/Prism instance. Doctor watches <code>logs/latest.log</code> while this tab is open.</p><div class="row"><button class="secondary" id="watchFolder">Start watch</button><button class="ghost" id="stopWatch">Stop</button></div><div id="watchStatus" class="scan-status">Stopped.</div></section><section class="lab-card"><h3>Quarantine</h3><div id="quarantineList" class="mini-list"></div><div class="row"><button class="secondary" id="quarantineSuspects">Add top suspects</button><button class="ghost" id="downloadQuarantine">Download manifest</button></div></section></div>
      <section class="lab-card"><div class="section-head"><h3>Automatic Fix Plan</h3><button class="ghost" id="refreshFixPlan">Refresh</button></div><div id="fixPlan"></div></section>
      <section class="lab-card"><div class="section-head"><h3>Binary Search Assistant</h3><button class="ghost" id="resetBinary">Reset</button></div><div id="binaryBox"></div></section>
      <div id="runtimeResults" class="lab-stack"></div>
    </div>
    <div class="lab-pane hidden" id="lab-health">
      <div id="overallHealth" class="lab-stack"></div><section class="lab-card"><div class="section-head"><h3>Benchmark snapshots</h3><button class="primary" id="saveBenchmark">Save current benchmark</button></div><p class="muted">Benchmarks are derived from logs: mod count, startup stalls, lag signals, memory signals and Doctor health. The browser does not benchmark Minecraft itself.</p><div id="benchmarkList"></div></section><section class="lab-card"><h3>What Changed? timeline</h3><div id="changeTimeline"></div></section>
    </div>
    <div class="lab-pane hidden" id="lab-tools">
      <div class="lab-grid two"><section class="lab-card"><h3>Issue report generator</h3><div class="row"><button class="primary" id="generateIssue">Generate sanitized report</button><button class="secondary" id="copyIssue">Copy</button><button class="ghost" id="downloadFullReport">Full pack report</button></div><textarea id="issueOutput" class="tool-text" placeholder="Generated Markdown will appear here…"></textarea></section><section class="lab-card"><h3>Privacy Redactor</h3><p class="muted">Removes common usernames, home paths, emails, IP addresses, UUIDs and obvious token fields before sharing.</p><div class="row"><button class="secondary" id="redactCurrent">Load sanitized current log</button><button class="secondary" id="redactText">Redact text</button></div><textarea id="redactor" class="tool-text" placeholder="Paste sensitive log text…"></textarea></section></div>
      <div class="lab-grid two"><section class="lab-card"><h3>Shareable diagnosis</h3><p class="muted">Creates a small diagnosis-only URL fragment. The full log is not included.</p><div class="row"><button class="primary" id="shareDiagnosis">Copy share link</button></div><div id="sharedDiagnosis"></div></section><section class="lab-card"><h3>Doctor CLI — browser edition</h3><pre id="cliOut" class="cli-output">Modpack Doctor Web CLI\nType: doctor help</pre><div class="cli-line"><span>›</span><input id="cliInput" placeholder="doctor status"></div></section></div>
      <section class="lab-card"><div class="section-head"><h3>Doctor Knowledge Base</h3><input id="kbSearch" class="kb-search" placeholder="Search mixin, Java, registry…"></div><div id="kbResults" class="kb-grid"></div></section>
    </div>`}
  function bind(){
    qs('#labToggle').onclick=()=>toggleLab(true);qs('#closeLab').onclick=()=>toggleLab(false);qsa('.lab-tab').forEach(b=>b.onclick=()=>switchLab(b.dataset.lab));
    qs('#pickPack').onclick=()=>qs('#packInput').click();qs('#packInput').onchange=e=>scanPicked(e.target.files,'current');qs('#pickFolder').onclick=()=>qs('#folderInput').click();qs('#folderInput').onchange=e=>scanFolderFiles(e.target.files);qs('#pickPrism').onclick=openPrism;
    qs('#pickWorking').onclick=()=>qs('#workingInput').click();qs('#workingInput').onchange=e=>scanSide(e.target.files[0],'working');qs('#pickBroken').onclick=()=>qs('#brokenInput').click();qs('#brokenInput').onchange=e=>scanSide(e.target.files[0],'broken');qs('#runDiff').onclick=runDiff;qs('#clientServer').onclick=clientServer;qs('#saveSnapshot').onclick=saveSnapshot;qs('#refreshSnapshots').onclick=renderSnapshots;
    qs('#saveFingerprint').onclick=()=>captureFingerprint(true);qs('#watchFolder').onclick=startWatch;qs('#stopWatch').onclick=stopWatch;qs('#quarantineSuspects').onclick=addSuspectsToQuarantine;qs('#downloadQuarantine').onclick=downloadQuarantine;qs('#refreshFixPlan').onclick=renderFixPlan;qs('#resetBinary').onclick=resetBinary;
    qs('#saveBenchmark').onclick=saveBenchmark;qs('#generateIssue').onclick=generateIssue;qs('#copyIssue').onclick=()=>copy(qs('#issueOutput').value,qs('#copyIssue'));qs('#downloadFullReport').onclick=downloadFullReport;qs('#redactCurrent').onclick=()=>{qs('#redactor').value=P.redact(core()?.text||qs('#logInput').value)};qs('#redactText').onclick=()=>{qs('#redactor').value=P.redact(qs('#redactor').value)};qs('#shareDiagnosis').onclick=shareDiagnosis;qs('#kbSearch').oninput=e=>renderKnowledge(e.target.value);qs('#cliInput').onkeydown=e=>{if(e.key==='Enter'){runCli(e.target.value);e.target.value=''}};
  }
  function toggleLab(show){qs('#doctorLab').classList.toggle('hidden',!show);if(show){qs('#doctorLab').scrollIntoView({behavior:'smooth',block:'start'});refreshRuntime();renderHealth();renderFixPlan()}}
  function switchLab(name){qsa('.lab-tab').forEach(b=>b.classList.toggle('active',b.dataset.lab===name));qsa('.lab-pane').forEach(p=>p.classList.toggle('hidden',p.id!==`lab-${name}`));if(name==='health')renderHealth();if(name==='debug'){refreshRuntime();renderBinary();renderFixPlan()}if(name==='diff')renderSnapshots()}
  async function scanPicked(files){if(!files?.length)return;const status=qs('#packStatus');status.textContent='Scanning… JAR metadata, dependencies, mixins and configs are being inspected.';try{let pack;if(files.length===1&&/\.(zip|mrpack|jar)$/i.test(files[0].name))pack=await P.scanArchive(files[0],qs('#packRole').value);else pack=await P.scanLooseFiles(files,qs('#packRole').value);P.state.current=pack;status.textContent=`Scanned ${pack.mods.length} top-level mods · fingerprint ${pack.fingerprint}`;renderPack(pack);renderFixPlan();renderHealth()}catch(e){status.textContent=`Scan failed: ${e.message}`}}
  async function scanFolderFiles(files){if(!files?.length)return;qs('#packStatus').textContent='Scanning selected folder…';try{const pack=await P.scanLooseFiles([...files],qs('#packRole').value,'Selected instance folder');P.state.current=pack;qs('#packStatus').textContent=`Folder scanned: ${pack.mods.length} mods · ${pack.textRecords.length} text/config/data files inspected.`;renderPack(pack);renderFixPlan();renderHealth()}catch(e){qs('#packStatus').textContent=`Folder scan failed: ${e.message}`}}
  async function openPrism(){if(!window.showDirectoryPicker){qs('#packStatus').textContent='Direct folder access is not available in this browser. Use Choose folder instead.';return}try{const handle=await showDirectoryPicker({mode:'read'});qs('#packStatus').textContent='Reading Prism/Minecraft instance folder…';const files=await Z.walkHandle(handle),pack=await P.scanLooseFiles(files,qs('#packRole').value,handle.name);P.state.current=pack;qs('#packStatus').textContent=`${pack.detected.prism?'Prism instance':'Folder'} scanned: ${pack.mods.length} mods.`;renderPack(pack);renderFixPlan();renderHealth()}catch(e){if(e.name!=='AbortError')qs('#packStatus').textContent=e.message}}
  function renderPack(pack){
    const a=pack.analysis,c=P.contentSummary(pack),mods=pack.mods.slice().sort((x,y)=>(a.risk[y.id]||0)-(a.risk[x.id]||0));
    qs('#packHealth').innerHTML=healthBars(a.health);
    const issues=a.issues.length?a.issues.slice(0,100).map(issueCard).join(''):'<div class="good-callout">No dependency/compatibility/config integrity problem was detected by the current rules.</div>';
    const rows=mods.slice(0,500).map(m=>`<tr><td><b>${h(m.id)}</b><small>${h(m.name)}</small></td><td>${h(m.version)}</td><td>${h(m.loader)}</td><td>${h(m.side)}</td><td>${m.deps?.length||0}</td><td><span class="risk risk-${riskBand(a.risk[m.id])}">${a.risk[m.id]||0}</span></td><td>${m.mixins?.reduce((n,x)=>n+(x.classes?.length||0),0)||0}</td></tr>`).join('');
    const access=pack.mods.filter(m=>m.access?.widener||m.access?.transformer).map(m=>`<div class="mini-row"><b>${h(m.id)}</b><span>${m.access?.widener?`AW ${m.access.widener.lines.length} entries`:''}${m.access?.widener&&m.access?.transformer?' · ':''}${m.access?.transformer?`AT ${m.access.transformer.lines.length} entries`:''}</span></div>`).join('')||'<p class="muted">No access widener/transformer metadata inspected.</p>';
    const embedded=pack.mods.filter(m=>m.embedded?.length).map(m=>`<div class="mini-row"><b>${h(m.id)}</b><span>${m.embedded.map(e=>`${h(e.id)} ${h(e.version)}`).join(' · ')}</span></div>`).join('')||'<p class="muted">No embedded JAR metadata found.</p>';
    const mixins=pack.mods.filter(m=>m.mixins?.length).sort((a,b)=>b.mixins.reduce((n,x)=>n+x.classes.length,0)-a.mixins.reduce((n,x)=>n+x.classes.length,0)).slice(0,60).map(m=>`<div class="mini-row"><b>${h(m.id)}</b><span>${m.mixins.length} config(s) · ${m.mixins.reduce((n,x)=>n+x.classes.length,0)} mixin classes</span></div>`).join('')||'<p class="muted">No mixin configs found in inspected metadata.</p>';
    qs('#packResults').innerHTML=`
      <section class="lab-card"><div class="section-head"><h3>Pack findings <span class="count-pill">${a.issues.length}</span></h3><span class="muted">${pack.detected.prism?'Prism instance · ':''}${pack.detected.world?'World structure · ':''}${pack.role}</span></div><div class="issue-grid">${issues}</div></section>
      <section class="lab-card"><div class="section-head"><h3>Dependency graph</h3><span class="muted">Top connected mods; lines point to installed dependencies.</span></div><div class="graph-wrap">${dependencyGraph(pack)}</div></section>
      <section class="lab-card"><div class="section-head"><h3>Mod inventory</h3><span class="muted">${fmt(pack.mods.length)} top-level · ${fmt(pack.embedded.length)} embedded</span></div><div class="table-wrap"><table class="mod-table"><thead><tr><th>Mod</th><th>Version</th><th>Loader</th><th>Side</th><th>Deps</th><th>Risk</th><th>Mixins</th></tr></thead><tbody>${rows}</tbody></table></div></section>
      <div class="lab-grid two"><section class="lab-card"><h3>Safe Boot Profile</h3><p class="muted">Libraries/core mods with the highest reverse-dependency importance. This is a conservative starting set, not a guaranteed bootable pack.</p><div class="tag-cloud">${a.safeBoot.slice(0,80).map(m=>`<span>${h(m.id)}</span>`).join('')||'<span>None inferred</span>'}</div></section><section class="lab-card"><h3>Content Doctor</h3><div class="metric-list"><div><span>Data JSON inspected</span><b>${c.dataFiles}</b></div><div><span>Asset JSON inspected</span><b>${c.assetFiles}</b></div><div><span>Config/JSON issues</span><b>${pack.configIssues.length}</b></div><div><span>Datapack paths</span><b>${c.datapackFiles}</b></div><div><span>World detected</span><b>${c.worldDetected?'YES':'NO'}</b></div></div><div class="content-kinds">${Object.entries(c.kinds).map(([k,v])=>`<span>${h(k)} <b>${v}</b></span>`).join('')}</div></section></div>
      <div class="lab-grid three"><section class="lab-card"><h3>Mixin surface map</h3>${mixins}</section><section class="lab-card"><h3>Access inspector</h3>${access}</section><section class="lab-card"><h3>Embedded JAR inspector</h3>${embedded}</section></div>`;
  }
  function riskBand(n=0){return n>=70?'high':n>=35?'medium':'low'}
  function issueCard(x){return `<article class="pack-issue ${severityClass(x.severity)}"><div><span class="severity-label">${h(x.severity)}</span><span class="confidence-small">${x.confidence||'?'}%</span></div><h4>${h(x.title)}</h4><p>${h(x.detail)}</p><details><summary>Why Doctor thinks this</summary><p>${h(confidenceExplanation(x))}</p></details>${x.mods?.length?`<button class="tiny" data-quarantine="${h(x.mods.join(','))}">Quarantine suspects</button>`:''}</article>`}
  function confidenceExplanation(x){const map={dependency:'The dependency was declared mandatory in inspected mod metadata but no matching mod ID exists in the inventory.',duplicate:'Multiple inspected JAR metadata files declare the same mod ID.',side:'The mod metadata explicitly declares an environment/side that conflicts with the selected pack role.',compatibility:'The installed IDs match a known high-overlap mod combination; this is a compatibility warning rather than proof of a crash.',mixin:'The same fully-qualified mixin class name appears in more than one inspected mod.',library:'Embedded JAR metadata contains multiple versions of the same embedded mod/library ID.',config:'The browser parsed the configuration text and found a structural/parse signal.'};return map[x.type]||'This finding combines inspected metadata and heuristic compatibility rules.'}
  function healthBars(o){return `<div class="health-bars">${Object.entries(o).map(([k,v])=>`<div><span>${h(k)}</span><i><b style="width:${v}%"></b></i><strong>${v}</strong></div>`).join('')}</div>`}
  function dependencyGraph(pack){
    const mods=pack.mods.slice().sort((a,b)=>(pack.analysis.reverse.get(b.id)?.size||0)-(pack.analysis.reverse.get(a.id)?.size||0)).slice(0,36),ids=new Set(mods.map(m=>m.id)),W=920,H=520,cx=W/2,cy=H/2,R=205,pos={};mods.forEach((m,i)=>{const a=Math.PI*2*i/mods.length-Math.PI/2;pos[m.id]={x:cx+Math.cos(a)*R,y:cy+Math.sin(a)*R}});let lines='';for(const m of mods)for(const d of m.deps||[])if(ids.has(d.id)){const a=pos[m.id],b=pos[d.id];lines+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/>`};const nodes=mods.map(m=>{const p=pos[m.id],risk=pack.analysis.risk[m.id]||0;return `<g><circle cx="${p.x}" cy="${p.y}" r="${12+risk/18}"/><text x="${p.x}" y="${p.y-18}" text-anchor="middle">${h(m.id.slice(0,18))}</text></g>`}).join('');return mods.length?`<svg viewBox="0 0 ${W} ${H}" class="dep-graph"><g class="edges">${lines}</g><g class="nodes">${nodes}</g></svg>`:'<p class="muted">No mod dependency metadata available.</p>'}
  async function scanSide(file,side){if(!file)return;const st=qs(`#${side}Status`),role=qs(`#${side}Role`).value;st.textContent='Scanning…';try{const pack=await P.scanArchive(file,role,file.name);P.state[side]=pack;st.textContent=`${pack.mods.length} mods · health ${pack.analysis.health.overall}/100 · ${pack.fingerprint}`;if(side==='broken')P.state.current=pack}catch(e){st.textContent=e.message}}
  function runDiff(){const a=P.state.working,b=P.state.broken;if(!a||!b){qs('#diffResults').innerHTML='<div class="warning-callout">Load both working and broken packs first.</div>';return}const d=P.diffPacks(a,b,core()),cd=P.configDiff(a,b);qs('#diffResults').innerHTML=`<section class="lab-card"><h3>Working → Broken changes</h3><div class="diff-summary"><div><b>${d.added.length}</b><span>added</span></div><div><b>${d.removed.length}</b><span>removed</span></div><div><b>${d.changed.length}</b><span>updated/changed</span></div><div><b>${cd.changed.length}</b><span>config changed</span></div></div>${diffList(d,cd)}</section><section class="lab-card"><h3>Suspect Ranking 2.0</h3><p class="muted">Combines pack changes, crash-log suspects and each changed mod's dependency/mixin blast radius.</p><div class="rank-list">${d.suspects.slice(0,30).map((s,i)=>`<div><strong>#${i+1} ${h(s.id)}</strong><span>score ${s.score} · ${h(s.reasons.join(' · '))}</span><button class="tiny" data-qone="${h(s.id)}">quarantine</button></div>`).join('')||'<p>No changed mod could be ranked.</p>'}</div></section>`;bindDynamic()}
  function diffList(d,cd){const item=(label,arr,fn)=>arr.length?`<div class="diff-block"><h4>${label}</h4>${arr.slice(0,120).map(fn).join('')}</div>`:'';return item('Added mods',d.added,m=>`<div class="mini-row"><b>+ ${h(m.id)}</b><span>${h(m.version)}</span></div>`)+item('Removed mods',d.removed,m=>`<div class="mini-row"><b>− ${h(m.id)}</b><span>${h(m.version)}</span></div>`)+item('Version/file changes',d.changed,x=>`<div class="mini-row"><b>↻ ${h(x.id)}</b><span>${h(x.from.version)} → ${h(x.to.version)}</span></div>`)+item('Changed configs',cd.changed,x=>`<div class="mini-row"><b>⚙ ${h(x.path)}</b><span>content hash changed</span></div>`)}
  function clientServer(){const a=P.state.working,b=P.state.broken;if(!a||!b){qs('#diffResults').innerHTML='<div class="warning-callout">Load a client pack and a server pack first.</div>';return}const client=a.role==='client'?a:b,server=a.role==='server'?a:b;if(client.role===server.role){qs('#diffResults').innerHTML='<div class="warning-callout">Set one pack role to Client and the other to Server.</div>';return}const C=new Map(client.mods.map(m=>[m.id,m])),S=new Map(server.mods.map(m=>[m.id,m])),serverMissing=[],clientOnlyOnServer=[],serverOnlyOnClient=[];for(const [id,m] of C)if(!S.has(id)&&!['client','client_only'].includes(String(m.side).toLowerCase()))serverMissing.push(m);for(const m of server.mods)if(['client','client_only'].includes(String(m.side).toLowerCase()))clientOnlyOnServer.push(m);for(const m of client.mods)if(['server','server_only'].includes(String(m.side).toLowerCase()))serverOnlyOnClient.push(m);qs('#diffResults').innerHTML=`<section class="lab-card"><h3>Client vs Server Doctor</h3><div class="diff-summary"><div><b>${serverMissing.length}</b><span>common/gameplay mods missing server-side</span></div><div><b>${clientOnlyOnServer.length}</b><span>client-only on server</span></div><div><b>${serverOnlyOnClient.length}</b><span>server-only on client</span></div></div>${['Missing on server',serverMissing,'Client-only installed on server',clientOnlyOnServer,'Server-only installed on client',serverOnlyOnClient].reduce((s,x,i,a)=>i%2?s+`<div class="diff-block"><h4>${a[i-1]}</h4>${x.slice(0,100).map(m=>`<div class="mini-row"><b>${h(m.id)}</b><span>${h(m.version)}</span></div>`).join('')||'<p class="muted">None</p>'}</div>`:s,'')}</section>`}
  function saveSnapshot(){const pack=P.state.current||P.state.broken;if(!pack)return alert('Scan a pack first.');const name=prompt('Snapshot name',pack.label)||pack.label;P.saveSnapshot(pack,name);renderSnapshots();renderHealth()}
  function renderSnapshots(){const box=qs('#snapshotList');if(!box)return;const snaps=P.snapshots(),current=P.state.current||P.state.broken;box.innerHTML=snaps.length?snaps.map(s=>`<div class="snapshot-row"><div><b>${h(s.name)}</b><span>${new Date(s.at).toLocaleString()} · ${s.mods.length} mods · ${s.fingerprint}</span></div><div><button class="tiny" data-rollback="${s.id}">Rollback plan</button></div></div>`).join(''):'<p class="muted">No snapshots yet.</p>';qsa('[data-rollback]').forEach(b=>b.onclick=()=>{const s=snaps.find(x=>x.id===b.dataset.rollback);if(!current)return alert('Scan the current pack first.');const r=P.rollbackPlan(s,current);qs('#diffResults').innerHTML=`<section class="lab-card"><h3>Rollback to ${h(s.name)}</h3><div class="diff-block"><h4>Restore</h4>${r.restore.map(x=>`<div class="mini-row"><span>${h(x)}</span></div>`).join('')||'<p>None</p>'}</div><div class="diff-block"><h4>Remove</h4>${r.remove.map(x=>`<div class="mini-row"><span>${h(x)}</span></div>`).join('')||'<p>None</p>'}</div><div class="diff-block"><h4>Version rollback</h4>${r.downgrade.map(x=>`<div class="mini-row"><span>${h(x)}</span></div>`).join('')||'<p>None</p>'}</div></section>`})}
  function captureFingerprint(save){const a=core();if(!a){qs('#fingerprintBox').textContent='Analyze a crash log first.';return}const fp=P.crashFingerprint(a.text);let msg=`${fp.hash} · ${fp.lines.length} normalized crash lines`;if(save){const r=P.saveCrashFingerprint(a.text,a.meta);if(r.best)msg+=` · closest previous crash: ${r.best.similarity}% similar (${new Date(r.best.at).toLocaleString()})`;else msg+=' · first stored crash fingerprint';}qs('#fingerprintBox').textContent=msg;renderHealth()}
  function candidateIds(){const pack=P.state.current||P.state.broken,a=core(),ids=[];if(P.state.lastDiff?.suspects?.length)ids.push(...P.state.lastDiff.suspects.slice(0,50).map(x=>x.id));if(pack&&a?.suspects)for(const s of a.suspects)for(const m of pack.mods)if(m.id.includes(s.name)||s.name.includes(m.id))ids.push(m.id);if(pack)for(const x of pack.analysis.issues)ids.push(...(x.mods||[]));return [...new Set(ids.filter(Boolean))].slice(0,80)}
  function startBinary(){const candidates=candidateIds();if(candidates.length<2){qs('#binaryBox').innerHTML='<div class="warning-callout">Need at least two suspect mods. Scan a pack and analyze a crash or run a working-vs-broken diff first.</div>';return}binary={candidates,round:1,history:[]};saveBinary();renderBinary()}
  function saveBinary(){localStorage.setItem('mdBinaryState',JSON.stringify(binary))}
  function resetBinary(){binary=null;localStorage.removeItem('mdBinaryState');renderBinary()}
  function renderBinary(){const box=qs('#binaryBox');if(!box)return;if(!binary){box.innerHTML='<p class="muted">The assistant repeatedly halves the suspect set. It never modifies your files: you disable the suggested group yourself, launch Minecraft, then report whether the crash remains.</p><button class="primary" id="startBinary">Start from current suspects</button>';qs('#startBinary').onclick=startBinary;return}if(binary.candidates.length<=1){const id=binary.candidates[0];box.innerHTML=`<div class="culprit"><span>LIKELY CULPRIT</span><strong>${h(id||'Unknown')}</strong><p>${binary.history.length} isolation round(s) completed. Re-test with only this mod changed before reporting a bug.</p><button class="secondary" id="binaryQuarantine">Add to quarantine</button></div>`;qs('#binaryQuarantine').onclick=()=>{if(id){quarantine.add(id);saveQuarantine()}};return}const half=Math.ceil(binary.candidates.length/2),A=binary.candidates.slice(0,half),B=binary.candidates.slice(half);box.innerHTML=`<div class="binary-head"><b>Round ${binary.round}</b><span>${binary.candidates.length} suspects remain</span></div><div class="binary-instruction">Temporarily <strong>disable Group A</strong>, then launch the pack.</div><div class="binary-groups"><div><h4>Group A · disable (${A.length})</h4><div class="tag-cloud">${A.map(x=>`<span>${h(x)}</span>`).join('')}</div></div><div><h4>Group B · keep enabled (${B.length})</h4><div class="tag-cloud">${B.map(x=>`<span>${h(x)}</span>`).join('')}</div></div></div><div class="row"><button class="danger-btn" id="binaryCrash">Crash still happens</button><button class="success-btn" id="binaryWorks">Pack works</button></div><p class="muted">Crash still happens → culprit is probably in enabled Group B. Pack works → culprit is probably in disabled Group A.</p>`;qs('#binaryCrash').onclick=()=>binaryAnswer('crash',A,B);qs('#binaryWorks').onclick=()=>binaryAnswer('works',A,B)}
  function binaryAnswer(result,A,B){binary.history.push({round:binary.round,result,disabled:A,enabled:B});binary.candidates=result==='works'?A:B;binary.round++;saveBinary();renderBinary()}
  function saveQuarantine(){localStorage.setItem('mdQuarantine',JSON.stringify([...quarantine]));renderQuarantine()}
  function addSuspectsToQuarantine(){candidateIds().slice(0,12).forEach(x=>quarantine.add(x));saveQuarantine()}
  function renderQuarantine(){const box=qs('#quarantineList');if(!box)return;box.innerHTML=quarantine.size?[...quarantine].map(x=>`<span class="q-tag">${h(x)} <button data-unq="${h(x)}">×</button></span>`).join(''):'<span class="muted">Empty</span>';qsa('[data-unq]').forEach(b=>b.onclick=()=>{quarantine.delete(b.dataset.unq);saveQuarantine()})}
  function downloadQuarantine(){download('modpack-doctor-quarantine.json',JSON.stringify({generated:new Date().toISOString(),mods:[...quarantine],note:'Move/disable these mods manually, then test. Modpack Doctor Web never modifies your instance.'},null,2),'application/json')}
  function bindDynamic(){qsa('[data-quarantine]').forEach(b=>b.onclick=()=>{b.dataset.quarantine.split(',').filter(Boolean).forEach(x=>quarantine.add(x));saveQuarantine()});qsa('[data-qone]').forEach(b=>b.onclick=()=>{quarantine.add(b.dataset.qone);saveQuarantine()})}
  function renderFixPlan(){const box=qs('#fixPlan');if(!box)return;const pack=P.state.current||P.state.broken,a=core(),steps=[],seen=new Set(),add=(text,confidence,kind)=>{if(seen.has(text))return;seen.add(text);steps.push({text,confidence,kind})};if(pack)for(const x of pack.analysis.issues){if(x.type==='dependency')add(`Install/restore the missing dependency reported by: ${x.detail}`,x.confidence,'metadata');else if(x.type==='duplicate')add(`Remove the duplicate JAR copy for ${x.mods?.[0]||'the duplicate mod ID'}.`,x.confidence,'metadata');else if(x.type==='side')add(`Move/remove the side-incompatible mod: ${x.detail}`,x.confidence,'metadata');else if(x.type==='compatibility')add(`Test without one member of the renderer/compatibility pair: ${x.detail}`,x.confidence,'compatibility');else if(x.type==='config')add(`Repair or regenerate ${x.title.replace('Config issue: ','')}: ${x.detail}`,x.confidence,'config')}
    if(a?.diagnoses)for(const d of a.diagnoses.slice(0,5))for(const f of d.fixes.slice(0,3))add(f,d.confidence,'crash log');const rt=a?P.runtimeDoctor(a.text,a.meta):null;if(rt?.java.status==='mismatch')add(rt.java.message,96,'runtime');if(rt?.memory.oom)add('Resolve memory exhaustion: verify Xmx, native memory pressure, resource packs/shaders, and possible leaks before raising allocation.',92,'runtime');if(P.state.lastDiff?.suspects?.length)add(`Start by testing the highest changed-mod suspect: ${P.state.lastDiff.suspects[0].id}.`,88,'diff');box.innerHTML=steps.length?`<ol class="fix-plan">${steps.slice(0,25).map(s=>`<li><span>${h(s.text)}</span><small>${s.confidence}% · ${h(s.kind)}</small></li>`).join('')}</ol>`:'<p class="muted">Analyze a log or scan a pack to build an ordered fix plan.</p>'}
  function refreshRuntime(){const box=qs('#runtimeResults'),a=core();if(!box)return;if(!a){box.innerHTML='<section class="lab-card"><p class="muted">Analyze a log to unlock Java Advisor, Memory Profiler, Startup Profiler, Performance Doctor, GPU/Shader, Registry/World, Access and Mixin diagnostics.</p></section>';return}const r=P.runtimeDoctor(a.text,a.meta);box.innerHTML=`<div class="lab-grid three">${runtimeCard('Java Advisor',r.java.message,[`Current: ${r.java.current||'?'}`,`Recommended: ${r.java.recommended||'?'}`],r.java.status==='mismatch'?'high':'good')}${runtimeCard('Memory Profiler',r.memory.message,[`Xmx: ${r.memory.xmx||'not found'}`,`Max GC pause: ${r.memory.gcMax?Math.round(r.memory.gcMax)+'ms':'n/a'}`],r.memory.oom?'high':'good')}${runtimeCard('Performance Doctor',r.performance.message,r.performance.examples,r.performance.signals?'medium':'good')}</div><div class="lab-grid three">${runtimeCard('GPU / Driver Hints',`${r.gpu.vendor}: ${r.gpu.message}`,r.gpu.errors,r.gpu.errors.length?'high':'good')}${runtimeCard('Shader Doctor',r.shader.length?`${r.shader.length} shader/render error lines detected.`:'No shader-specific error lines.',r.shader,r.shader.length?'medium':'good')}${runtimeCard('Registry & World Doctor',`${r.registry.length} registry · ${r.world.length} world/chunk signal(s).`,[...r.registry.slice(0,4),...r.world.slice(0,4)],r.registry.length||r.world.length?'medium':'good')}</div><div class="lab-grid two">${runtimeCard('Access Widener / Transformer Log Inspector',`${r.access.length} access-related log signal(s).`,r.access,r.access.length?'medium':'good')}${runtimeCard('Mixin Conflict Map · runtime',`${r.mixin.length} mixin-related crash line(s).`,r.mixin,r.mixin.length?'high':'good')}</div><section class="lab-card"><h3>Startup Profiler</h3>${r.startup.gaps.length?`<div class="gap-list">${r.startup.gaps.map(g=>`<div><b>${(g.ms/1000).toFixed(2)}s gap</b><span>around line ${g.line}</span><code>${h(g.after.slice(0,180))}</code></div>`).join('')}</div>`:'<p class="muted">No ≥500 ms timestamp gap could be derived from this log format.</p>'}</section>`}
  function runtimeCard(title,msg,items,status){return `<section class="lab-card runtime-card ${status}"><h3>${h(title)}</h3><p>${h(msg)}</p>${items?.length?`<ul>${items.slice(0,8).map(x=>`<li>${h(x)}</li>`).join('')}</ul>`:''}</section>`}
  async function startWatch(){if(!window.showDirectoryPicker){qs('#watchStatus').textContent='Folder Watch requires the File System Access API (Chrome/Edge).';return}try{watchHandle=await showDirectoryPicker({mode:'read'});const logs=await watchHandle.getDirectoryHandle('logs');const fh=await logs.getFileHandle('latest.log');stopWatch();watchHandle={root:watchHandle,file:fh};qs('#watchStatus').textContent='Watching logs/latest.log every 4 seconds while this tab stays open.';async function poll(){try{const f=await watchHandle.file.getFile(),stamp=`${f.lastModified}:${f.size}`;if(stamp!==watchStamp){watchStamp=stamp;const text=await f.text();qs('#logInput').value=text;qs('#logInput').dispatchEvent(new Event('input'));qs('#analyzeBtn').click();qs('#watchStatus').textContent=`New log read ${new Date().toLocaleTimeString()} · ${fmt(f.size)} bytes`}}catch(e){qs('#watchStatus').textContent=`Watch error: ${e.message}`}}await poll();watchTimer=setInterval(poll,4000)}catch(e){if(e.name!=='AbortError')qs('#watchStatus').textContent=e.message}}
  function stopWatch(){if(watchTimer)clearInterval(watchTimer);watchTimer=null;watchStamp='';if(qs('#watchStatus'))qs('#watchStatus').textContent='Stopped.'}
  function renderHealth(){const box=qs('#overallHealth');if(!box)return;const pack=P.state.current||P.state.broken,a=core(),rt=a?P.runtimeDoctor(a.text,a.meta):null;let runtimeHealth=100;if(a)runtimeHealth=a.health;if(rt?.memory.oom)runtimeHealth-=20;if(rt?.performance.signals)runtimeHealth-=Math.min(25,rt.performance.signals*3);if(rt?.gpu.errors.length)runtimeHealth-=20;runtimeHealth=Math.max(0,runtimeHealth);box.innerHTML=`<section class="lab-card"><h3>Pack Health Dashboard</h3>${pack?healthBars({...pack.analysis.health,runtime:runtimeHealth}):`<div class="health-bars"><div><span>runtime log</span><i><b style="width:${runtimeHealth}%"></b></i><strong>${runtimeHealth}</strong></div></div><p class="muted">Scan a pack to add dependency, compatibility, config and integrity categories.</p>`}</section>`;renderBenchmarks();renderTimeline()}
  function saveBenchmark(){const a=core(),pack=P.state.current||P.state.broken;if(!a&&!pack)return alert('Analyze a log or scan a pack first.');const rt=a?P.runtimeDoctor(a.text,a.meta):null,arr=JSON.parse(localStorage.getItem('mdBenchmarks')||'[]'),b={at:new Date().toISOString(),pack:pack?.label||'log only',fingerprint:pack?.fingerprint||null,mods:pack?.mods.length||+(a?.meta?.modCount||0)||null,packHealth:pack?.analysis.health.overall??null,logHealth:a?.health??null,startupGap:rt?.startup.maxGap||null,lagSignals:rt?.performance.signals||0,xmx:rt?.memory.xmx||null};arr.unshift(b);localStorage.setItem('mdBenchmarks',JSON.stringify(arr.slice(0,40)));renderBenchmarks();renderTimeline()}
  function renderBenchmarks(){const box=qs('#benchmarkList');if(!box)return;const arr=JSON.parse(localStorage.getItem('mdBenchmarks')||'[]');box.innerHTML=arr.length?`<div class="table-wrap"><table class="mod-table"><thead><tr><th>Date</th><th>Pack</th><th>Mods</th><th>Pack health</th><th>Log health</th><th>Largest startup gap</th><th>Lag</th><th>Xmx</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${new Date(x.at).toLocaleString()}</td><td>${h(x.pack)}</td><td>${x.mods??'—'}</td><td>${x.packHealth??'—'}</td><td>${x.logHealth??'—'}</td><td>${x.startupGap?`${(x.startupGap/1000).toFixed(2)}s`:'—'}</td><td>${x.lagSignals}</td><td>${h(x.xmx||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">No benchmark snapshots saved.</p>'}
  function renderTimeline(){const box=qs('#changeTimeline');if(!box)return;const snaps=P.snapshots().map(x=>({at:x.at,title:`Pack snapshot · ${x.name}`,detail:`${x.mods.length} mods · health ${x.health?.overall??'?'}/100`})),crashes=JSON.parse(localStorage.getItem('mdCrashHistory')||'[]').map(x=>({at:x.at,title:`Crash · ${x.fp.hash}`,detail:`${x.meta?.loader||'Unknown loader'} ${x.meta?.mc||''}`})),bench=JSON.parse(localStorage.getItem('mdBenchmarks')||'[]').map(x=>({at:x.at,title:`Benchmark · ${x.pack}`,detail:`${x.mods??'?'} mods · startup gap ${x.startupGap?Math.round(x.startupGap)+'ms':'n/a'}`}));const all=[...snaps,...crashes,...bench].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,60);box.innerHTML=all.length?`<div class="timeline">${all.map(x=>`<div><i></i><section><b>${h(x.title)}</b><span>${new Date(x.at).toLocaleString()}</span><p>${h(x.detail)}</p></section></div>`).join('')}</div>`:'<p class="muted">Snapshots, fingerprints and benchmarks will build a local change timeline here.</p>'}
  function generateIssue(){qs('#issueOutput').value=P.issueReport(core(),P.state.current||P.state.broken)}
  function downloadFullReport(){const pack=P.state.current||P.state.broken;if(!pack)return alert('Scan a pack first.');download('modpack-doctor-full-report.md',P.oneClickReport(pack,core()),'text/markdown')}
  function shareDiagnosis(){const a=core(),pack=P.state.current||P.state.broken;if(!a&&!pack)return alert('Analyze a log or scan a pack first.');const payload={v:1,at:new Date().toISOString(),meta:a?.meta||null,logHealth:a?.health??null,diagnoses:a?.diagnoses?.slice(0,6).map(d=>({title:d.title,severity:d.severity,confidence:d.confidence}))||[],suspects:a?.suspects?.slice(0,8).map(s=>({name:s.name,score:s.score}))||[],pack:pack?{mods:pack.mods.length,health:pack.analysis.health.overall,fingerprint:pack.fingerprint,issues:pack.analysis.issues.slice(0,8).map(x=>({title:x.title,severity:x.severity,confidence:x.confidence}))}:null};const raw=encodeURIComponent(JSON.stringify(payload)),enc=btoa(unescape(raw)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const url=`${location.origin}${location.pathname}#diagnosis=${enc}`;copy(url,qs('#shareDiagnosis'));qs('#sharedDiagnosis').innerHTML='<div class="good-callout">Share link copied. It contains diagnosis summary only — not the full log.</div>'}
  function consumeShare(){if(!location.hash.startsWith('#diagnosis='))return;try{let s=location.hash.slice(11).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const p=JSON.parse(decodeURIComponent(escape(atob(s))));qs('#sharedDiagnosis').innerHTML=`<div class="shared-card"><b>Shared diagnosis · ${new Date(p.at).toLocaleString()}</b><p>${p.meta?`${h(p.meta.loader)} · Minecraft ${h(p.meta.mc)} · Java ${h(p.meta.java)}`:'Pack-only share'}</p><div class="tag-cloud">${(p.diagnoses||[]).map(x=>`<span>${h(x.title)} · ${x.confidence}%</span>`).join('')}${p.pack?`<span>Pack health ${p.pack.health}/100 · ${p.pack.mods} mods</span>`:''}</div></div>`;toggleLab(true);switchLab('tools')}catch{}}
  function renderKnowledge(q){const box=qs('#kbResults');if(!box)return;q=String(q||'').toLowerCase().trim();const rows=knowledge.filter(x=>!q||x.join(' ').toLowerCase().includes(q));box.innerHTML=rows.map(([t,d,f])=>`<article><h4>${h(t)}</h4><p>${h(d)}</p><strong>Doctor action</strong><p>${h(f)}</p></article>`).join('')||'<p class="muted">No knowledge-base entry matched.</p>'}
  function runCli(cmd){const out=qs('#cliOut'),a=core(),pack=P.state.current||P.state.broken;cmd=cmd.trim().replace(/^doctor\s+/i,'').toLowerCase();let r='';if(!cmd||cmd==='help')r='Commands: help, status, pack, suspects, issues, fingerprint, health, java, memory, performance, snapshots, quarantine, redact, report, clear';else if(cmd==='status')r=`log=${a?'analyzed':'none'} pack=${pack?pack.label:'none'} diff=${P.state.lastDiff?'ready':'none'} watch=${watchTimer?'on':'off'}`;else if(cmd==='pack')r=pack?`${pack.mods.length} mods + ${pack.embedded.length} embedded · ${pack.fingerprint}\n${pack.mods.slice(0,40).map(m=>`${m.id}@${m.version}`).join('\n')}`:'No pack scanned.';else if(cmd==='suspects')r=a?.suspects?.map((s,i)=>`#${i+1} ${s.name} score=${s.score} ${s.reasons.join(', ')}`).join('\n')||'No suspects.';else if(cmd==='issues')r=pack?.analysis.issues.map(x=>`[${x.severity}] ${x.title} — ${x.detail}`).join('\n')||'No pack issues.';else if(cmd==='fingerprint')r=a?P.crashFingerprint(a.text).hash:'Analyze a log first.';else if(cmd==='health')r=pack?JSON.stringify(pack.analysis.health,null,2):a?`log health ${a.health}/100`:'No health data.';else if(cmd==='java')r=a?P.runtimeDoctor(a.text,a.meta).java.message:'Analyze a log first.';else if(cmd==='memory')r=a?JSON.stringify(P.runtimeDoctor(a.text,a.meta).memory,null,2):'Analyze a log first.';else if(cmd==='performance')r=a?JSON.stringify(P.runtimeDoctor(a.text,a.meta).performance,null,2):'Analyze a log first.';else if(cmd==='snapshots')r=P.snapshots().map(x=>`${x.at} ${x.name} ${x.fingerprint}`).join('\n')||'No snapshots.';else if(cmd==='quarantine')r=[...quarantine].join('\n')||'Quarantine empty.';else if(cmd==='redact')r=P.redact(a?.text||qs('#logInput').value).slice(0,10000);else if(cmd==='report')r=pack?P.oneClickReport(pack,a):a?.report||'No report data.';else if(cmd==='clear'){out.textContent='Modpack Doctor Web CLI';return}else r=`Unknown command: ${cmd}. Try: doctor help`;out.textContent+=`\n\n› doctor ${cmd}\n${r}`;out.scrollTop=out.scrollHeight}
  init();
  document.addEventListener('click',e=>{const b=e.target.closest('[data-quarantine]');if(b){b.dataset.quarantine.split(',').filter(Boolean).forEach(x=>quarantine.add(x));saveQuarantine()}const q=e.target.closest('[data-qone]');if(q){quarantine.add(q.dataset.qone);saveQuarantine()}});
})();
